### ISSUE TITLE
Reprovide all provides from a directory

### ISSUE THREAD

**Issue by bennn** [AlexKnauth/reprovide-lang#9] opened 2017-09-18 17:58 UTC
feature request: reproviding a `path-string?` that refers to a directory reprovides from all files in the directory.

So if I had a directory `dir/` with files `a.rkt` and `b.rkt`, then:

```
#lang reprovide
"dir/" ;; or something like `(all-from-directory "dir/")`
```

Should be the same as:

```
#lang racket/base

(require "dir/a.rkt" "dir/b.rkt")
(provide (all-from-out "dir/a.rkt" "dir/b.rkt"))
```

- - - 

Typed Racket does something like this here:
https://github.com/racket/typed-racket/blob/master/typed-racket-lib/typed-racket/static-contracts/combinators.rkt

**Comment by AlexKnauth** [comment] 2017-09-18 22:05
I want to keep it as close to the syntax of `require` as possible. Would it be okay if instead we made `all-from-directory` as a normal require-transformer, and allowed using it in `#lang reprovide` modules?

(Edit: Or to follow the convention of require-transformers, `directory-in`?)

**Comment by bennn** [comment] 2017-09-19 02:49
Yes, `directory-in`  would be good

**Comment by AlexKnauth** [comment] 2017-09-19 03:03
What types of files should `directory-in` try to require? In the example you gave the code only requires files with a `.rkt` extension, which is fine for a private TR thing, but I'm not sure that's what this should do. Should it instead include all the files which can be read as valid modules, either `#lang` files or `(module ...)` s-expressions?

**Comment by AlexKnauth** [comment] 2017-09-19 03:52
How should I properly reference the directory relative to the path of the file the way require would? I see a few options:

 - Relative to `(current-directory)`: really bad, breaks whenever it's compiled from a different directory
 - Relative to the path given by `syntax-source`: really bad, breaks when a macro generates it
 - Somehow use `define-runtime-path`? I don't know how I would get it to refer to the correct thing...
 - Somehow use `convert-relative-module-path` or `current-require-module-path`: This seems like it should be the Right Way, but `convert-relative-module-path` is just returning the same path I'm giving it, which ends up behaving just like if I used (current-directory), and `current-require-module-path` is false within my require transformer.

**Comment by bennn** [comment] 2017-09-19 04:14
For types of files, I think `.rkt`. Maybe `.rkt` can be the default and `directory-in` can take an optional suffix.
Or maybe `(glob-in glob-str)` for more freedom (even `(glob-in "parent-dir/**/*.rkt")`)

`(define-runtime-path directory-in-cwd ".")` seems best offhand .. maybe `syntax-local-lift-module-end-declaration` will put it in the right place. I guess another problem is that each use of `(directory-in ...)` will need to either:
- decide whether to add a `define-runtime-path`, based on some state
- create a new `define-runtime-path` and use a new identifier

I don't know `convert-relative-module-path`.

**Comment by kstrafe** [comment] 2018-11-18 16:19
Any updates on this? I'd like to see globbing.

**Comment by AlexKnauth** [comment] 2018-11-18 17:42
I don't have globbing right now, but I do have `directory-in` working now in the [directory-in](https://github.com/AlexKnauth/reprovide-lang/blob/directory-in/reprovide/require-transformer/directory-in.rkt) branch.

**Comment by AlexKnauth** [comment] 2018-11-18 19:03
@bennn Is there a "quoting" operation for globs? A `glob-quote`, that would be analogous to `regexp-quote`? I want to make sure that if glob-special characters appear in the parent directory they will be encoded in the correct way; that I can make a glob match exactly those characters and not interpret them as glob-special characters.

**Comment by bennn** [comment] 2018-11-19 15:29
There's no `glob-quote`. That would be a good to have.

I can try to add it this week.

**Comment by AlexKnauth** [comment] 2018-11-19 18:17
Just added `glob-in` as a require form that can be used within `#lang reprovide`. I'll still leave this open until I get to making documentation for it eventually.

**Comment by kstrafe** [comment] 2018-11-20 00:58
What about `directory-in`, will that be merged in?

**Comment by AlexKnauth** [comment] 2018-11-20 01:29
Probably not. I technically “works” as in it does generate a require for every file in the given directory. However, this is unlikely to make sense as-is. It literally generates a require for every file that has `#lang` at the top, even if it that file was intended to be a text file, an auto save file, a preproccessor template, or anything else. When users use `glob-in` that won’t be as much of a problem because they will probably specify the file-extensions they want explicitly.

**Comment by AlexKnauth** [comment] 2018-11-22 20:26
I've added some initial [documentation](https://docs.racket-lang.org/reprovide/index.html#%28part._.Extra_require_forms%29) with a few examples and a pointer to the docs for [Globbing](https://docs.racket-lang.org/file/glob.html), so I think now I can close this.

**Closed as completed by AlexKnauth** 2018-11-22 20:26 UTC

**Comment by bennn** [comment] 2018-11-23 23:25
proposed `glob-quote` : https://github.com/racket/racket/pull/2397

**Comment by jackfirth** [comment] 2019-06-27 06:04
Hey folks, just stumbled across `glob-in` and wanted to say it's _really awesome_ 🎉 Thank you all!
